### ISSUE TITLE
Usage notes?

### ISSUE THREAD

**Issue by kubukoz** [zbelzer/fitness-core#1]
I'm very curious about this app, and will take a look in my free time, but maybe it'd be a good idea to add some usage notes to make it easier for people to get started with :P

**Comment by zbelzer** [comment]
Haha, ok. It's a bit, well, rough, right now.

The idea is to generate a large sampling of workouts meeting some basic criteria, for example, a time budget in my initial design, and then to score those workouts based on various other requirements.

Initial thoughts:
- At least one exercise from each muscle group
- A score where a max value was no overlap in exercises and least value was perfect overlap
- A score which is determined by the workout meeting a minimal volume in each muscle as to stay on track with a goal.

Right now, I need sample workouts to really see if any of the algorithms I come up with make any sense.

There's no real "usage notes" as it just got to the state of generating a single sample workout without any scoring. Ideally, I get some basic scoring going, add Play to the project (I'm originally a Rails dev, so I'd like to build a site in Play) and add a dead simple interface to it.

Soo, well, work in progress I guess.

**Comment by kubukoz** [comment]
Play is pretty simple IMO - one of the first Scala frameworks I have worked with. Good luck! :)

**Comment by zbelzer** [comment]
I've only been writing Scala for 6 months or so, so if you see anything worth improving as I go along, please let me know.

**Comment by kubukoz** [comment]
Sure thing! (although it's not been much longer in my case)
